
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: passw0rd

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults:false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
      
